### ISSUE TITLE
CSP Error - Conflict with PWA

### ISSUE THREAD

**Issue by Triloworld** [jmblog/nuxt-netlify-http2-server-push#6]
Hello, this module work find standalone.
Right now it has this: https://github.com/jmblog/nuxt-netlify-http2-server-push/blob/891d36189618cc6494e57dc580ff310dcc8927dc/lib/module.js#L27

This "/*" is issue as any file (image, js, css) will have added <link> header.
When workbox is used, this generate CSP error and double request. 
I added it locally and change it to "/" so only my homepage getting header. 
Can we have better solution to handle that situation? Maybe I just miss some configuration? 

To see problem just install as depedency:
- this module
- https://github.com/nuxt-community/pwa-module | https://pwa.nuxtjs.org/

Because we have only one simple pattern then we need for every link create list of headers? That will be big blob which isn't better option

**Comment by Triloworld** [comment]
There will be new release?

**Comment by jmblog** [comment]
@Triloworld Yes, I've released `v0.1.3`. Please check it out!
